services:
  postgres-common:
    image: postgres:latest
    container_name: common-postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=common_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  postgres-cart:
    image: postgres:latest
    container_name: cart-postgres
    depends_on:
      - postgres-common
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=cart_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  postgres-store:
    image: postgres:latest
    container_name: store-postgres
    depends_on:
      - postgres-common
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=store_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  postgres-user:
    image: postgres:latest
    container_name: user-postgres
    depends_on:
      - postgres-common
    ports:
      - 5436:5432
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  postgres-ai:
    image: postgres:latest
    container_name: ai-postgres
    depends_on:
      - postgres-common
    ports:
      - 5437:5432
    environment:
      - POSTGRES_DB=ai_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  postgres-auth:
    image: postgres:latest
    container_name: auth-postgres
    depends_on:
      - postgres-common
    ports:
      - 5438:5432
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  postgres-payment:
    image: postgres:latest
    container_name: payment-postgres
    depends_on:
      - postgres-common
    ports:
      - 5439:5432
    environment:
      - POSTGRES_DB=payment_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - 6379:6379

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka