server:
  port: 8011

spring:
  application:
    name: module-common
  batch:
      job:
        enabled: false
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

#  eureka:
#    instance:
#      prefer-ip-address: true
#    client:
#      register-with-eureka: true
#      fetch-registry: true
#      serviceUrl:
#        defaultZone: http://localhost:8761/eureka/

  datasource:
    url: ${LOCAL_DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  cloud:
    config:
      enabled: false


