server:
  port: 8017

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always     # 상세 정보 표시
  health:
    db:
      enabled: false           # DB 체크 비활성화
    redis:
      enabled: false

logging:
  level:
    org.springframework.cloud.gateway: WARN
    reactor.netty: WARN
    root: WARN

spring:
  application:
    name: payment-service

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
      idle-timeout: 300000        # 5m
      max-lifetime: 1500000       # 25m
      keepalive-time: 1200000     # 20m
      connection-timeout: 30000
      validation-timeout: 3000
      auto-commit: false
  cloud:
    config:
      enabled: false

  springdoc:
    api-docs:
      version: openapi_3_1
      enabled: true
    enable-spring-security: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

toss:
  secret-key: ${TOSS_SECRET}
  webhook-secret: ${TOSS_WEBHOOK_SECRET:webhook_secret_key}
  base-url: ${TOSS_BASE_URL:https://api.tosspayments.com}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false

kafka:
  topics:
    paymentCommands: payment.commands.v1
    paymentEvents: payment.events.v1
    orderEvents: order.events.v1
    inventoryEvents: inventory.events.v1

    paymentCommandsDLQ: payment.commands.dlq.v1

app:
  eventPublishEnabled: ${EVENT_PUBLISH_ENABLED:true}
  outbox:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        failureRateThreshold: 50
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 10s
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        maxWaitDurationInHalfOpenState: 0
        waitDurationInOpenState: 10s
    instances:
      reservation-service-circuit-breaker:
        base-config: default
      user-service:
        base-config: default

passport:
  secret-key: ${PASSPORT_SECRET}
