server:
  port: 8016

spring:
  application:
    name: ai-service

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

    eureka:
      instance:
        prefer-ip-address: true
      client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/


  datasource:
    url: ${LOCAL_DB_URL}
    driver-class-name: org.postgresql.Driver
    #    driver-class-name: org.h2.Driver # 테스트용
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  cloud:
    config:
      enabled: false

  springdoc:
    api-docs:
      version: openapi_3_1
      enabled: true
    enable-spring-security: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json



management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

weather:
  api:
    key: ${WEATHER_API_KEY:}
    url: https://api.openweathermap.org/data/2.5/weather

gemini:
  api:
    key: ${GEMINI_API_KEY:}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent


logging:
  level:
    root: ${LOG_LEVEL:INFO}

