package com.example.cloudfour.cartservice.domain.order.enums;

public enum OrderStatus {
    PENDING,
    INVENTORY_CONFIRMED,
    INVENTORY_INSUFFICIENT,
    INVENTORY_RELEASED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    PAYMENT_CANCELED,
    ORDER_ACCEPTED,
    COOKING,
    DELIVERY_ASSIGNED,
    DELIVERING,
    DELIVERED,
    ORDER_CANCELED
}
