server:
  port: 8012

logging:
  level:
    org.springframework.cloud.gateway: WARN
    reactor.netty: WARN
    root: WARN

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always     # 상세 정보 표시
  health:
    db:
      enabled: false           # DB 체크 비활성화
    redis:
      enabled: false

spring:
  application:
    name: cart-service

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
      idle-timeout: 300000        # 5m
      max-lifetime: 1500000       # 25m
      keepalive-time: 1200000     # 20m
      connection-timeout: 30000
      validation-timeout: 3000
      auto-commit: false

  cache:
    type: redis
    redis:
      time-to-live: 1800000

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms

  cloud:
    config:
      enabled: false

    springdoc:
      api-docs:
        version: openapi_3_1
        enabled: true
      enable-spring-security: true
      default-consumes-media-type: application/json
      default-produces-media-type: application/json


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false

kafka:
  topics:
    orderEvents: order.events.v1
    orderCommands: order.commands.v1
    paymentEvents: payment.events.v1

    orderCommandsDLQ: order.commands.dlq.v1

app:
  eventPublishEnabled: ${EVENT_PUBLISH_ENABLED:true}
  outbox:
    enabled: true
  saga:
    enabled: true


order:
  timeout:
    minutes: 0.17  # 주문 타임아웃 시간 (분) - 10초(테스트용) 실제로는 10분

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        failureRateThreshold: 50
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 10s
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        maxWaitDurationInHalfOpenState: 0
        waitDurationInOpenState: 10s
    instances:
      reservation-service-circuit-breaker:
        base-config: default
      user-service:
        base-config: default

passport:
  secret-key: ${PASSPORT_SECRET}
