server:
  port: 8012

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: cart-service

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  cache:
    type: redis
    redis:
      time-to-live: 1800000

  datasource:
    url: ${LOCAL_DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  cloud:
    config:
      enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false

passport:
  secret-key: ${PASSPORT_SECRET}

  springdoc:
    api-docs:
      version: openapi_3_1
      enabled: true
    enable-spring-security: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

kafka:
  topics:
    orderEvents: order.events.v1
    orderCommands: order.commands.v1
    paymentEvents: payment.events.v1

    orderCommandsDLQ: order.commands.dlq.v1

app:
  eventPublishEnabled: ${EVENT_PUBLISH_ENABLED:true}
  outbox:
    enabled: true
  saga:
    enabled: true

logging:
  level:
    org.springframework.cache: DEBUG
    com.example.cloudfour.cartservice.client: DEBUG

order:
  timeout:
    minutes: 0.17  # 주문 타임아웃 시간 (분) - 10초(테스트용) 실제로는 10분
    
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        failureRateThreshold: 50
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 10s
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        maxWaitDurationInHalfOpenState: 0
        waitDurationInOpenState: 10s
    instances:
      reservation-service-circuit-breaker:
        base-config: default
      user-service:
        base-config: default




