server:
  port: 8013

spring:
  application:
    name: store-service

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

    eureka:
      instance:
        prefer-ip-address: true
      client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/

  springdoc:
    api-docs:
      version: openapi_3_1
      enabled: true
    enable-spring-security: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

  data:
    mongodb:
      uri: ${MONGO_URI}
  datasource:
    url: ${LOCAL_DB_URL}
    driver-class-name: org.postgresql.Driver
    #    driver-class-name: org.h2.Driver # 테스트용
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  cloud:
    config:
      enabled: false